/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as DespesasRouteImport } from './routes/despesas'
import { Route as FluxoRouteImport } from './routes/fluxo'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as MovimentacoesRouteImport } from './routes/movimentacoes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const DespesasRoute = DespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxoRoute = FluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesRoute = MovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cartoes': typeof CartoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/despesas': typeof DespesasRoute
  '/fluxo': typeof FluxoRoute
  '/investimentos': typeof InvestimentosRoute
  '/metas': typeof MetasRoute
  '/movimentacoes': typeof MovimentacoesRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cartoes'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/fluxo'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cartoes'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/fluxo'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/cartoes'
    | '/configuracoes'
    | '/contas'
    | '/despesas'
    | '/fluxo'
    | '/investimentos'
    | '/metas'
    | '/movimentacoes'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartoesRoute: typeof CartoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  DespesasRoute: typeof DespesasRoute
  FluxoRoute: typeof FluxoRoute
  InvestimentosRoute: typeof InvestimentosRoute
  MetasRoute: typeof MetasRoute
  MovimentacoesRoute: typeof MovimentacoesRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despesas': {
      id: '/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof DespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxo': {
      id: '/fluxo'
      path: '/fluxo'
      fullPath: '/fluxo'
      preLoaderRoute: typeof FluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes': {
      id: '/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof MovimentacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartoesRoute: CartoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  DespesasRoute: DespesasRoute,
  FluxoRoute: FluxoRoute,
  InvestimentosRoute: InvestimentosRoute,
  MetasRoute: MetasRoute,
  MovimentacoesRoute: MovimentacoesRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
